### PR TITLE
re-add share withholding attack

### PR DESCRIPTION
**Pull request by leonardojobim**
Update answer about share withholding attack based on the articles "Share Withholding Attack in Blockchain Mining" and "Reward distribution mechanisms and withholding attacks in Bitcoin pool mining.

### CODE REVIEW

**Comment by adamjonas** [comment]
This is clearly a superior answer. Can you delete my version starting on line 12?

**Comment by leonardojobim** [comment]
I had forgotten to remove the other answer. Thanks.

**Comment by adamjonas** [comment]
I merged murtyjones' answer on block withholding - sorry to cause you more work, but can you add your question back to the main question page on mining-network-prop/README.md and then I think it might have a small conflict in the answers file? Thanks!

**Review by murtyjones — APPROVED** [review]
Nicely laid out!

**Pull request merged**
