### PR TITLE
Expound on answer about block withholding

### PR DESCRIPTION
**Pull request by murtyjones**
- Adds some more context around why a miner would engage in block withholding
- Changes the "share withholding" term to "block withholding" to avoid confusion around a [slightly different attack]https://arxiv.org/pdf/2008.13317.pdf).) than the one covered in the Rosenfeld paper

### CODE REVIEW

**Comment by murtyjones** [comment]
@adamjonas is this update OK or should i close it out?

**Comment by adamjonas** [comment]
A share withholding and a block withholding are entirely different, so I've been going back and forth on whether it's worth the swap. Let's poll the group this week.

**Comment by adamjonas** [comment]
@murtyjones Any more conviction after this week's discussion?

**Comment by murtyjones** [comment]
> @murtyjones Any more conviction after this week's discussion?

When we covered this section in our small groups study, the answerer did a nice a job explaining share withholding and linked off to [this one-pager](https://www.dropbox.com/s/0bh0rxhe4866603/share_withholding_attack.pdf?dl=0). I'm thinking that maybe it makes more sense to keep the question and add this to the reading materials (since it's pretty short) just to make sure readers don't conflate the two. What do you think?

**Comment by adamjonas** [comment]
@leonardojobim would you be cool with adding your answer? I think adding it inline would be preferable to linking.

**Comment by adamjonas** [comment]
https://github.com/chaincodelabs/study-groups/pull/51 handles share withholding

**Pull request merged**
