### PR TITLE
Add coin selection video link

### PR DESCRIPTION
**Pull request by hebasto**

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
LGTM, though since the video is 26 minutes, maybe update the time (or provide two times, i.e. `20/30`)

**Comment by hebasto** [comment]
> LGTM, though since the video is 26 minutes, maybe update the time (or provide two times, i.e. `20/30`)

That was my first thought, but the transcript actually covers 20 minutes of video, w/o Q&A :)

**Comment by adamjonas** [comment]
I'd prefer that you add the link to the [transcript](https://github.com/kanzure/diyhpluswiki/blob/b730608f3a9dc2b34fedee6882e2b499f2e6fdcc/transcripts/scalingbitcoin/tokyo-2018/edgedevplusplus/coin-selection.mdwn). This is how most other transcript/videos are presented in the repo.

**Comment by hebasto** [comment]
> I'd prefer that you add the link to the [transcript](https://github.com/kanzure/diyhpluswiki/blob/b730608f3a9dc2b34fedee6882e2b499f2e6fdcc/transcripts/scalingbitcoin/tokyo-2018/edgedevplusplus/coin-selection.mdwn). This is how most other transcript/videos are presented in the repo.

Cannot follow you. A transcript link currently is present in the master branch. This PR just adds a video link while preserving the transcript link.

**Comment by adamjonas** [comment]
I mean something like [this](https://diyhpl.us/wiki/transcripts/scalingbitcoin/stanford-2017/edgeplusplus/p2p-john-newbery/) where the video is found on the transcript and people can choose to watch from there. The only alternatives that are offered on the same line in this curriculum are when resources are actually different (e.g. book chapter versus talk or one talk versus another).

**Comment by hebasto** [comment]
Closed in favor of https://github.com/kanzure/diyhpluswiki/pull/207.

**Comment by kanzure** [comment]
Thank you.

**Pull request closed without merging**
